# Exercise 5.17

In [1]:
import numpy as np
from IPython.display import display, Math
from scipy import stats

In [2]:
X = np.array([[117], [62], [21]])
n = X.sum()
q = X.shape[0]

In [3]:
# Compute the p-hat vector.
p = X/n
p

array([[0.585],
       [0.31 ],
       [0.105]])

In [4]:
# Compute the covariance matrix.
S = -p @ p.T
np.fill_diagonal(S, p*(1 - p))
S

array([[ 0.242775, -0.18135 , -0.061425],
       [-0.18135 ,  0.2139  , -0.03255 ],
       [-0.061425, -0.03255 ,  0.093975]])

In [5]:
alpha = 0.05

In [6]:
crit_chi2 = stats.chi2.ppf(1-alpha, q)
crit_chi2

7.814727903251179

## Simultaneous 95% confidence intervals

$$
\textbf{a}^{\prime} \hat{\textbf{p}}
\pm
\sqrt{\chi_{q}^{2}(\alpha)}
\sqrt{\frac{\textbf{a}^{\prime} \textbf{S} \textbf{a}}{n}}
$$

In [7]:
# Create matrix A to store the three vectors used in the simultaneous CI's.
A = np.eye(q)

In [8]:
# Initialize the matrix to store the simultaneous CI for the proportions.
ci = np.zeros((q, 2))
for i in range(A.shape[0]):
    # Pull a column from A.
    a = A[:,i]
    # Compute the 95% CI for a proportion using the result on page 265.
    ci[i, :] = a.T @ p + np.array([-1, 1]) * np.sqrt(crit_chi2) * np.sqrt(a.T @ S @ a /n)

In [9]:
for i in range(ci.shape[0]):
    display(Math(fr'{p[i,0]:.2f} \pm \sqrt{{{crit_chi2:.2f}}} \frac{{\sqrt{{{S[i,i]:.2f}}}}}{{\sqrt{{{n}}}}}\hspace{{0.5cm}} \text{{contains}}'\
                     fr'\hspace{{0.5cm}}p_{i+1}\hspace{{1cm}}\text{{or}}\hspace{{1cm}}{ci[i,0]:.2f} \leq p_{i+1} \leq {ci[i,1]:.2f}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

Could also compute the CI for $p_{3}$ using $p_{3} = 1 - (p_{1} + p_{2})$. We get the same answer as above.

In [10]:
(1 - (p[0] + p[1])) + np.array([-1, 1]) * np.sqrt(crit_chi2) * np.sqrt(((p[0] + p[1])*(1-(p[0] + p[1])))/n)

array([0.04440342, 0.16559658])