In [1]:
import pathlib
import numpy as np
import pandas as pd
from IPython.display import display, Math
from scipy import stats
from chapter_5_utils import simult_conf_int, bonferroni_conf_int

In [2]:
def load_data() -> pd.DataFrame:
    # Load the bone material content data from page 43.
    fpath = pathlib.WindowsPath(r'..\..\data\Table1.8.xlsx')
    return pd.read_excel(fpath)

In [3]:
bone_df = load_data()
bone_df.head(3)

subject number  Dominant radius  Radius  Dominant humerus  Humerus   
0               1            1.103   1.052             2.139    2.238  \
1               2            0.842   0.859             1.873    1.741   
2               3            0.925   0.873             1.887    1.809   

   Dominant ulna   Ulna  
0          0.873  0.872  
1          0.590  0.744  
2          0.767  0.713

In [4]:
X = bone_df.to_numpy()[:,1:]
n, p = X.shape
alpha = 0.05

In [5]:
xbar = np.mean(X, axis=0).reshape(p, 1)
S = np.cov(X, rowvar=False)
f_crit = stats.f.ppf(1-alpha, dfn=p, dfd=n-p)
const = ((n-1)*p)/(n-p)

In [6]:
xbar

array([[0.8438 ],
       [0.81832],
       [1.79268],
       [1.73484],
       [0.7044 ],
       [0.69384]])

In [7]:
S

array([[0.01300158, 0.01037844, 0.02234997, 0.02008567, 0.00912071,
        0.00795784],
       [0.01037844, 0.01141789, 0.01853519, 0.02109951, 0.00852978,
        0.00890851],
       [0.02234997, 0.01853519, 0.08035723, 0.0667762 , 0.01683692,
        0.01284703],
       [0.02008567, 0.02109951, 0.0667762 , 0.06948447, 0.01773548,
        0.0167936 ],
       [0.00912071, 0.00852978, 0.01683692, 0.01773548, 0.01156842,
        0.00807115],
       [0.00795784, 0.00890851, 0.01284703, 0.0167936 , 0.00807115,
        0.01059914]])

## The 95% $T^{2}$ simultaneous confidence intervals:

$$
\bar{x}_{i}
\pm
\sqrt{
    \frac{(n-1)p}{(n-p)}
    F_{p, n-p}\left(\alpha\right)
}
\sqrt{
    \frac{s_{ii}}{n}
}
$$

In [8]:
# Computed by-hand as a check.
# xbar + np.array([-1, 1]) * np.sqrt(const*f_crit)*np.sqrt(np.diag(S).reshape(p, 1)/n)

In [9]:
simult_ci = simult_conf_int(X, alpha=0.05)
simult_ci

array([[0.74201787, 0.94558213],
       [0.72293801, 0.91370199],
       [1.53964193, 2.04571807],
       [1.49954252, 1.97013748],
       [0.60839135, 0.80040865],
       [0.60194144, 0.78573856]])

In [10]:
for i in range(simult_ci.shape[0]):
    display(Math(fr'{xbar[i,0]:.2f} \pm \sqrt{{{const*f_crit:.2f}}} '\
                 fr'\frac{{\sqrt{{{S[i,i]:.2f}}}}}{{\sqrt{{{n}}}}}\hspace{{0.5cm}} \text{{contains}}'\
                 fr'\hspace{{0.5cm}}\mu_{i+1}\hspace{{1cm}}\text{{or}}'\
                 fr'\hspace{{1cm}}{simult_ci[i,0]:.2f} \leq \mu_{i+1} '\
                 fr'\leq {simult_ci[i,1]:.2f}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## The 95% Bonferroni confidence intervals:

$$
\bar{x}_{i}
\pm
t_{n-1}
\left(\frac{\alpha}{2m}\right)
\sqrt{
    \frac{
            s_{ii}
        }{
            n
        }
    }

In [11]:
m = p
t_crit = stats.t.ppf(1-(alpha/(2*m)), n-1)

In [12]:
# Computed by-hand as a check.
# xbar + np.array([-1, 1]) * t_crit * np.sqrt(np.diag(S).reshape(p, 1)/n)

In [13]:
bonfer_ci = bonferroni_conf_int(X, alpha=alpha, m=m)
bonfer_ci

array([[0.77823377, 0.90936623],
       [0.75687662, 0.87976338],
       [1.62967739, 1.95568261],
       [1.58326556, 1.88641444],
       [0.64255294, 0.76624706],
       [0.63464059, 0.75303941]])

In [14]:
print(f'Bonferroni confidence intervals for the {p} mean lengths')
for i in range(bonfer_ci.shape[0]):
    display(Math(fr'{xbar[i,0]:.2f} \pm {t_crit:.2f} \frac{{\sqrt{{{S[i,i]:.2f}}}}}'\
                 fr'{{\sqrt{{{n}}}}}\hspace{{0.5cm}} \text{{contains}}'\
                 fr'\hspace{{0.5cm}}\mu_{i+1}\hspace{{1cm}}\text{{or}}'\
                 fr'\hspace{{1cm}}{bonfer_ci[i,0]:.2f} \leq \mu_{i+1} '\
                 fr'\leq {bonfer_ci[i,1]:.2f}'))

Bonferroni confidence intervals for the 6 mean lengths


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>