# Example 6.6 (The approximate $T^{2}$ distribution when $ \Sigma_{1} \ne \Sigma_{2}$)

In [1]:
import numpy as np
import numpy.linalg as la
from collections import namedtuple
from IPython.display import Math, display
from scipy import stats

Samples of sizes $n_{1} = 45$ and $n_{2} = 55$ were taken of Wisconsin
homeowners with and without air conditioning, respectively. (Data courtesy of Statistical
Laboratory, University of Wisconsin.) Two measurements of electrical usage
(in kilowatt hours) were considered. The first is a measure of total on-peak consumption
($X_{1}$) during July, and the second is a measure of total off-peak consumption
( $X_{2}$) during July.

In [2]:
n1 = 45
n2 = 55

In [3]:
xbar1 = np.array([[204.4], [556.6]])
xbar2 = np.array([[130.0], [355.0]])
p = xbar1.shape[0]

In [4]:
S1 = np.array([[13825.3, 23823.4], [23823.4, 73107.4]])
S2 = np.array([[ 8632.0, 19616.7], [19616.7, 55964.5]])

$$
\frac{1}{n_{1}} \textbf{S}_{1}
$$

In [5]:
(1/n1)*S1

array([[ 307.22888889,  529.40888889],
       [ 529.40888889, 1624.60888889]])

$$
\frac{1}{n_{2}} \textbf{S}_{2}
$$

In [6]:
(1/n2)*S2

array([[ 156.94545455,  356.66727273],
       [ 356.66727273, 1017.53636364]])

$$
{\left[
    \frac{1}{n_{1}} \textbf{S}_{1}
    +
    \frac{1}{n_{2}} \textbf{S}_{2}
\right]}^{-1}
$$

In [7]:
la.inv((1/n1)*S1 + (1/n2)*S2)

array([[ 0.00598739, -0.00200795],
       [-0.00200795,  0.00105187]])

$$
\frac{1}{n_{1}} \textbf{S}_{1}
{\left[
    \frac{1}{n_{1}} \textbf{S}_{1}
    +
    \frac{1}{n_{2}} \textbf{S}_{2}
\right]}^{-1}
$$

In [8]:
(1/n1)*S1 @ la.inv((1/n1)*S1 + (1/n2)*S2)

array([[ 0.77647483, -0.06002961],
       [-0.09234853,  0.64585273]])

$$
{\left(
    \frac{1}{n_{1}} \textbf{S}_{1}
    {\left[
        \frac{1}{n_{1}} \textbf{S}_{1}
        +
        \frac{1}{n_{2}} \textbf{S}_{2}
    \right]}^{-1}
\right)}^{2}
$$

In [9]:
la.matrix_power((1/n1)*S1 @ la.inv((1/n1)*S1 + (1/n2)*S2), 2)

array([[ 0.60845681, -0.08538177],
       [-0.13134985,  0.42266939]])

$$
\frac{1}{n_{2}} \textbf{S}_{2}
{\left[
    \frac{1}{n_{1}} \textbf{S}_{1}
    +
    \frac{1}{n_{2}} \textbf{S}_{2}
\right]}^{-1}
$$

In [10]:
(1/n2)*S2 @ la.inv((1/n1)*S1 + (1/n2)*S2)

array([[0.22352517, 0.06002961],
       [0.09234853, 0.35414727]])

$$
{\left(
    \frac{1}{n_{2}} \textbf{S}_{2}
    {\left[
        \frac{1}{n_{1}} \textbf{S}_{1}
        +
        \frac{1}{n_{2}} \textbf{S}_{2}
    \right]}^{-1}
\right)}^{2}
$$

In [11]:
la.matrix_power((1/n2)*S2 @ la.inv((1/n1)*S1 + (1/n2)*S2), 2)

array([[0.05550715, 0.03467745],
       [0.0533472 , 0.13096394]])

$$
\frac{1}{n_{1}}
\left\{
    \text{tr}
    \left[
        {\left(
            \frac{1}{n_{1}} \textbf{S}_{1}
            {\left(
                \frac{1}{n_{1}} \textbf{S}_{1}
                +
                \frac{1}{n_{2}} \textbf{S}_{2}
            \right)}^{-1}
        \right)}^{2}
    \right]
    +
    {\left(
        \text{tr}
        \left[
            \frac{1}{n_{1}} \textbf{S}_{1}
                {\left(
                    \frac{1}{n_{1}} \textbf{S}_{1}
                    +
                    \frac{1}{n_{2}} \textbf{S}_{2}
                \right)}^{-1}
        \right]
    \right)}^{2}
\right\}
$$

In [12]:
a = (1/n1)*(np.trace(la.matrix_power((1/n1)*S1 @ la.inv((1/n1)*S1 + (1/n2)*S2), 2)) +\
        np.trace((1/n1)*S1 @ la.inv((1/n1)*S1 + (1/n2)*S2))**2)
a

0.06786981982503869

$$
\frac{1}{n_{2}}
\left\{
    \text{tr}
    \left[
        {\left(
            \frac{1}{n_{2}} \textbf{S}_{2}
            {\left(
                \frac{1}{n_{1}} \textbf{S}_{1}
                +
                \frac{1}{n_{2}} \textbf{S}_{2}
            \right)}^{-1}
        \right)}^{2}
    \right]
    +
    {\left(
        \text{tr}
        \left[
            \frac{1}{n_{2}} \textbf{S}_{2}
                {\left(
                    \frac{1}{n_{1}} \textbf{S}_{1}
                    +
                    \frac{1}{n_{2}} \textbf{S}_{2}
                \right)}^{-1}
        \right]
    \right)}^{2}
\right\}
$$

In [13]:
b = (1/n2)*(np.trace(la.matrix_power((1/n2)*S2 @ la.inv((1/n1)*S1 + (1/n2)*S2), 2)) +\
        np.trace((1/n2)*S2 @ la.inv((1/n1)*S1 + (1/n2)*S2))**2)
b

0.009457755109839695

$$
\nu
=
\frac{p + p^{2}}
{
    \frac{1}{n_{1}}
    \left\{
        \text{tr}
        \left[
            {\left(
                \frac{1}{n_{1}} \textbf{S}_{1}
                {\left(
                    \frac{1}{n_{1}} \textbf{S}_{1}
                    +
                    \frac{1}{n_{2}} \textbf{S}_{2}
                \right)}^{-1}
            \right)}^{2}
        \right]
        +
        {\left(
            \text{tr}
            \left[
                \frac{1}{n_{1}} \textbf{S}_{1}
                    {\left(
                        \frac{1}{n_{1}} \textbf{S}_{1}
                        +
                        \frac{1}{n_{2}} \textbf{S}_{2}
                    \right)}^{-1}
            \right]
        \right)}^{2}
    \right\}
    +
    \frac{1}{n_{2}}
    \left\{
        \text{tr}
        \left[
            {\left(
                \frac{1}{n_{2}} \textbf{S}_{2}
                {\left(
                    \frac{1}{n_{1}} \textbf{S}_{1}
                    +
                    \frac{1}{n_{2}} \textbf{S}_{2}
                \right)}^{-1}
            \right)}^{2}
        \right]
        +
        {\left(
            \text{tr}
            \left[
                \frac{1}{n_{2}} \textbf{S}_{2}
                    {\left(
                        \frac{1}{n_{1}} \textbf{S}_{1}
                        +
                        \frac{1}{n_{2}} \textbf{S}_{2}
                    \right)}^{-1}
            \right]
        \right)}^{2}
    \right\}
}
$$

In [14]:
nu = (p + p**2)/(a+b)
nu

77.5919845547066

$$
\frac{\nu p}{\nu - (p - 1)}
F_{p, \nu - (p - 1)}(\alpha)
$$

In [15]:
alpha = 0.05
f_crit = nu*p/ (nu - (p - 1))*stats.f.ppf(1 - alpha, dfn=p, dfd=nu - (p - 1))
f_crit

6.313406609436447

$$
T^{2}
=
{\left[ \bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2} \right]}^{\prime}
{\left[
    \frac{1}{n_{1}} \textbf{S}_{1}
    +
    \frac{1}{n_{2}} \textbf{S}_{2}
\right]}^{-1}
\left[ \bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2} \right]
$$

In [16]:
# Computing T^{2} from Exanple 6.5.
T2 = ((xbar1 - xbar2).T @ la.inv((1/n1)*S1 + (1/n2)*S2) @ (xbar1 - xbar2)).item()
T2

15.658529097464307

In [23]:
if T2 > f_crit:
    display(Math(fr'\text{{We have that }} T^{{2}} = {T2:.3f} > \frac{{\nu p}}{{\nu - (p - 1)}}F_{{p, \nu - (p - 1)}}(\alpha) = '
                 fr'{f_crit:.3f} \text{{, so we would reject the null hypothesis that }} '
                 r'\bm{\mu}_{1} - \bm{\mu}_{2} = \textbf{0}'))
else:
    display(Math(fr'\text{{We have that }} T^{{2}} = {T2:.3f} \leq \frac{{\nu p}}{{\nu - (p - 1)}}F_{{p, \nu - (p - 1)}}(\alpha) = '
                 fr'{f_crit:.3f} \text{{, so we would fail to reject the null hypothesis that }} '
                 r'\bm{\mu}_{1} - \bm{\mu}_{2} = \textbf{0}'))

<IPython.core.display.Math object>