# Example 6.10

In [1]:
import numpy as np
import numpy.linalg as la
from IPython.display import display, Math
from scipy import stats

- $X_{1} = $ cost of nursing labor
- $X_{2} = $ cost of dietary labor
- $X_{3} = $ cost of plant operation and maintenance labor
- $X_{4} = $ cost of housekeeping and laundry labor.

Group
- $\ell = 1$: private
- $\ell = 2$: nonprofit
- $\ell = 3$: government

In [2]:
n1, n2, n3 = 271, 138, 107
n = n1 + n2 + n3
p, g = 4, 3
xbar1 = np.array([2.066, 0.480, 0.082, 0.360])[:,np.newaxis]
xbar2 = np.array([2.167, 0.596, 0.124, 0.418])[:,np.newaxis]
xbar3 = np.array([2.273, 0.521, 0.125, 0.383])[:,np.newaxis]

In [3]:
S1 = np.array([[ 0.291, 0.000, 0.000, 0.000],
               [-0.001, 0.011, 0.000, 0.000],
               [ 0.002, 0.000, 0.001, 0.000],
               [ 0.010, 0.003, 0.000, 0.010]])
S1 = np.tril(S1) + np.tril(S1, -1).T

S2 = np.array([[0.561, 0.000, 0.000, 0.000],
               [0.011, 0.025, 0.000, 0.000],
               [0.001, 0.004, 0.005, 0.000],
               [0.037, 0.007, 0.002, 0.019]])
S2 = np.tril(S2) + np.tril(S2, -1).T

S3 = np.array([[0.261,  0.000, 0.000, 0.000],
               [0.030,  0.017, 0.000, 0.000],
               [0.003, -0.000, 0.004, 0.000],
               [0.018,  0.006, 0.001, 0.013],])
S3 = np.tril(S3) + np.tril(S3, -1).T

In [4]:
W = (n1 - 1)*S1 + (n2 - 1)*S2 + (n3 - 1)*S3
W

array([[183.093,   4.417,   0.995,   9.677],
       [  4.417,   8.197,   0.548,   2.405],
       [  0.995,   0.548,   1.379,   0.38 ],
       [  9.677,   2.405,   0.38 ,   6.681]])

In [5]:
xbar = (n1*xbar1 + n2*xbar2 + n3*xbar3)/n
xbar

array([[2.13593605],
       [0.51952519],
       [0.10214922],
       [0.38028101]])

In [6]:
B = n1*(xbar1 - xbar) @ (xbar1 - xbar).T + n2*(xbar2 - xbar) @ (xbar2 - xbar).T + n3*(xbar3 - xbar) @ (xbar3 - xbar).T
B

array([[3.46879889, 1.09857133, 0.81067792, 0.58595027],
       [1.09857133, 1.23067867, 0.45003356, 0.61573385],
       [0.81067792, 0.45003356, 0.23178351, 0.23112936],
       [0.58595027, 0.61573385, 0.23112936, 0.30859425]])

In [7]:
lmbda_star = la.det(W)/(la.det(B + W))
lmbda_star

0.7627582047406533

In [8]:
display(Math(r'\Lambda^{\star}'
             '='
             r'\frac{\left|\textbf{W}\right|}{\left|\textbf{B} + \textbf{W}\right|}'
             '='
             f'{lmbda_star:.4f}'
             ))

<IPython.core.display.Math object>

In [9]:
display(Math(fr'\text{{Since}} \hspace{{0.2cm}} p = {p}'
             fr'\hspace{{0.2cm}} \text{{and}} \hspace{{0.2cm}} '
             fr'g = {g} \hspace{{0.2cm}} \text{{using Table 6.3}},'
             r'\left( \frac{ \sum n_{\ell} - p - 2 }{ p } \right)'
             r'\left( \frac{ 1 - \sqrt{\Lambda^{\star}} }{ \sqrt{\Lambda^{\star}} } \right)'
             r'\sim F_{2p, 2(\sum n_{\ell} - p - 2)}'
             ))
# 

<IPython.core.display.Math object>

In [10]:
test_stat = ((n - p - 2)/p)*((1 - np.sqrt(lmbda_star))/np.sqrt(lmbda_star))
alpha = 0.01
f_crit = stats.f.ppf(1 - alpha, dfn=2*p, dfd=2*(n-p-2))
chi2_crit = stats.chi2.ppf(1 - alpha, df=2*p)/(2*p)

In [11]:
display(Math(r'F^{\star} = \left( \frac{ \sum n_{\ell} - p - 2 }{ p } \right)'
             r'\left( \frac{ 1 - \sqrt{\Lambda^{\star}} }{ \sqrt{\Lambda^{\star}} } \right)'
             '='
             fr'\left( \frac{{ {n} - {p} - 2 }}{{ {p} }} \right)'
             fr'\left( \frac{{ 1 - \sqrt{{ {lmbda_star:.4f} }} }}{{ \sqrt{{ {lmbda_star:.4f} }} }} \right)'
             '='
             f'{test_stat:.4f}'
             ))

<IPython.core.display.Math object>

In [12]:
display(Math(fr'F_{{\text{{crit}}}} = F_{{2(g-1), 2(\sum n_{{\ell}} - g - 1)}}'
             '='
             fr'F_{{2({g}-1), 2({n} - {g} - 1)}} \left( {alpha} \right)'
             '='
             fr'F_{{{2*(g-1)}, {2*(n-g-1)} }} \left( {alpha} \right)'
             '='
             f'{f_crit:.3f}'
             ))

<IPython.core.display.Math object>

In [13]:
if test_stat > f_crit:
    display(Math(fr'\text{{We have that }} F^{{\star}} = {test_stat:.3f} > F_{{\text{{crit}}}} = F_{{{2*p}, {2*(n-p-2)} }} \left( {alpha} \right) \doteq '
                 fr'\chi^{{2}}_{{{2*p}}} \left( {alpha} \right)/{2*p} = {chi2_crit:.3f} \text{{, so we would reject the null hypothesis that }} '
                 r'\bm{\tau}_{1} = \bm{\tau}_{3} = \bm{\tau}_{3} = \textbf{0}'))
else:
    display(Math(fr'\text{{We have that }} F^{{\star}} = {test_stat:.3f} \leq F_{{\text{{crit}}}} = F_{{{2*p}, {2*(n-p-2)} }} \left( {alpha} \right) \doteq '
                 fr'\chi^{{2}}_{{{2*p}}} \left( {alpha} \right)/{2*p} = {chi2_crit:.3f} \text{{, so we would fail to reject the null hypothesis that }} '
                 r'\bm{\tau}_{1} = \bm{\tau}_{3} = \bm{\tau}_{3} = \textbf{0}'))

<IPython.core.display.Math object>

## The Bartlett test for $\sum{n}_{\ell} = n$ large

$$
\begin{align*}
H_{0}\text{: } & \bm{\tau}_{1} = \bm{\tau}_{2} = \bm{\tau}_{3} = \textbf{0} \\
H_{1}\text{: } & \text{at least one } \bm{\tau}_{\ell} \ne \textbf{0}
\end{align*}
$$

In [14]:
test_stat_bartlett = - (n - 1 - ((p + g)/2))*np.log(lmbda_star)
chi2_crit_bartlett = stats.chi2.ppf(1 - alpha, df=p*(g-1))

In [15]:
display(Math(r'X^{2\star}'
             '='
             r' - \left(n - 1 - \frac{ (p + g) }{ 2 }\right)'
             r'\left( \frac{ 1 - \sqrt{\Lambda_{\star}} }{ \sqrt{\Lambda_{\star}} } \right)'
             '='
             fr'- \left({n} - 1 - \frac{{ ({p} + {g}) }}{{ 2 }}\right)'
             fr'\left( \frac{{ 1 - \sqrt{{ {lmbda_star:.4f} }} }}{{ \sqrt{{ {lmbda_star:.4f} }} }} \right)'
             '='
             f'{test_stat_bartlett:.4f}'
             ))

<IPython.core.display.Math object>

In [16]:
display(Math(fr'X_{{\text{{crit}}}}^{{2}} = \chi_{{ p(g-1) }}^{{2}}'
             '='
             fr'\chi_{{ {p}({g}-1) }}^{{2}} \left( {alpha} \right)'
             '='
             fr'\chi_{{ {p*(g-1)} }}^{{2}} \left( {alpha} \right)'
             '='
             f'{chi2_crit_bartlett:.3f}'
             ))

<IPython.core.display.Math object>

In [17]:
if test_stat_bartlett > chi2_crit_bartlett:
    display(Math(fr'\text{{We have that }} X^{{2\star}} = {test_stat_bartlett:.3f} > '
                 r'X_{\text{crit}}^{2}'
                 '='
                 fr'\chi^{{2}}_{{{p*(g-1)}}} \left( {alpha} \right) = {chi2_crit_bartlett:.3f}'
                 r'\text{{, so we would reject the null hypothesis that }} '
                 r'\bm{\tau}_{1} = \bm{\tau}_{3} = \bm{\tau}_{3} = \textbf{0}'
                 ))
else:
    display(Math(fr'\text{{We have that }} X^{{2\star}} = {test_stat_bartlett:.3f} \leq '
                 r'X_{\text{crit}}^{2}'
                 '='
                 fr'\chi^{{2}}_{{{p*(g-1)}}} \left( {alpha} \right) = {chi2_crit_bartlett:.3f}'
                 r'\text{{, so we would fail to reject the null hypothesis that }} '
                 r'\bm{\tau}_{1} = \bm{\tau}_{3} = \bm{\tau}_{3} = \textbf{0}'
                 ))

<IPython.core.display.Math object>