# Example 6.5

In [1]:
import numpy as np
import pandas as pd
import numpy.linalg as la
from collections import namedtuple
from IPython.display import Math, display
from scipy import stats

Samples of sizes $n_{1} = 45$ and $n_{2} = 55$ were taken of Wisconsin
homeowners with and without air conditioning, respectively. (Data courtesy of Statistical
Laboratory, University of Wisconsin.) Two measurements of electrical usage
(in kilowatt hours) were considered. The first is a measure of total on-peak consumption
($X_{1}$) during July, and the second is a measure of total off-peak consumption
( $X_{2}$) during July.

In [2]:
n1 = 45
n2 = 55

In [3]:
xbar1 = np.array([[204.4], [556.6]])
xbar2 = np.array([[130.0], [355.0]])
p = xbar1.shape[0]
alpha = 0.05

In [4]:
S1 = np.array([[13825.3, 23823.4], [23823.4, 73107.4]])
S2 = np.array([[ 8632.0, 19616.7], [19616.7, 55964.5]])

$$
\frac{1}{n_{1}} \textbf{S}_{1}
+
\frac{1}{n_{2}} \textbf{S}_{2}
$$

In [5]:
(1/n1)*S1 + (1/n2)*S2

array([[ 464.17434343,  886.07616162],
       [ 886.07616162, 2642.14525253]])

In [6]:
a1 = np.array([1,0])
a2 = np.array([0,1])

In [7]:
xbard = xbar1 - xbar2

From Result 6.4 on page 292,
$$
\textbf{a}^{\prime} (\bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2})
\pm
\sqrt{
    \chi_{p}^{2}(\alpha)
}
\sqrt{
    \textbf{a}^{\prime}
    \left(
        \frac{1}{n_{1}}
        \textbf{S}_{1}
        +
        \frac{1}{n_{2}}
        \textbf{S}_{2}
    \right)
    \textbf{a}
}
$$

In [8]:
chi2_value = stats.chi2.ppf(1-alpha, df=p)

In [9]:
ci1 = (a1.T @ xbard) + np.array([-1, 1]) * np.sqrt(chi2_value) * np.sqrt(a1.T @ ((1/n1)*S1 + (1/n2)*S2) @ a1 )
ci1

array([ 21.66401492, 127.13598508])

In [10]:
ci2 = (a2.T @ xbard) + np.array([-1, 1]) * np.sqrt(chi2_value) * np.sqrt(a2.T @ ((1/n1)*S1 + (1/n2)*S2) @ a2 )
ci2

array([ 75.78140198, 327.41859802])

In [11]:
# Something to store information about the CI variables.
LabelCI = namedtuple('LabelCI', ['Text', 'Math'])
ci95_labels = [LabelCI(Text='on-peak', Math=r'\mu_{11} - \mu_{21}'),
               LabelCI(Text='off-peak', Math=r'\mu_{12} - \mu_{22}')]

In [12]:
# Display the results like on page 293.
display(Math(f'{ci95_labels[0].Math}:'
                fr'{xbard[0,0]:.1f}'
                fr'\pm \sqrt{{{chi2_value:.2f}}} '
                fr'\sqrt{{ {a1 @ ((1/n1)*S1 + (1/n2)*S2) @ a1:.2f} }}'
                r'\hspace{0.4cm}\text{or}\hspace{0.4cm}'
                fr'({ci1[0]:.1f}, {ci1[1]:.1f})'))

display(Math(f'{ci95_labels[1].Math}:'
                fr'{xbard[1,0]:.1f}'
                fr'\pm \sqrt{{{chi2_value:.2f}}} '
                fr'\sqrt{{ {a2 @ ((1/n1)*S1 + (1/n2)*S2) @ a2:.2f} }}'
                r'\hspace{0.4cm}\text{or}\hspace{0.4cm}'
                fr'({ci2[0]:.1f}, {ci2[1]:.1f})'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

Computing the $T^{2}$ statistic for testing $H_{0}: \bm{\mu}_{1} - \bm{\mu}_{2} = \textbf{0}$,
$$
T^{2}
=
{\left[ \bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2} \right]}^{\prime}
{\left[
    \frac{1}{n_{1}} \textbf{S}_{1}
    +
    \frac{1}{n_{2}} \textbf{S}_{2}
\right]}^{-1}
\left[ \bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2} \right]
$$

In [13]:
T2 = (xbard.T @ la.inv((1/n1)*S1 + (1/n2)*S2) @ xbard).item()
T2

15.658529097464307

In [14]:
if T2 > chi2_value:
    display(Math(fr'\text{{We have that }} T^{{2}} = {T2:.2f} > \chi_{{p}}^{{2}}(\alpha) = '
                 fr'{chi2_value:.2f} \text{{, so we would reject the null hypothesis that }} '
                 r'\bm{\mu}_{1} - \bm{\mu}_{2} = \textbf{0}'))
else:
    display(Math(fr'\text{{We have that }} T^{{2}} = {T2:.2f} \leq \chi_{{p}}^{{2}}(\alpha) = '
                 fr'{chi2_value:.2f} \text{{, so we would fail to reject the null hypothesis that }} '
                 r'\bm{\mu}_{1} - \bm{\mu}_{2} = \textbf{0}'))

<IPython.core.display.Math object>

In [15]:
crit_lc = la.inv((1/n1)*S1 + (1/n2)*S2) @ xbard
crit_lc

array([[0.04066  ],
       [0.0626658]])

In [16]:
covx1mx2inv = np.round(la.inv((1/n1)*S1 + (1/n2)*S2)*10000,3)
display('The most critical linear combination leading to the rejection of H0 has coefficient vector')
display(Math(r'\hat{\textbf{a}} \propto '
             r'\left( \frac{1}{n_{1}} \textbf{S}_{1} + \frac{1}{n_{2}} \textbf{S}_{2} \right)'
             r'(\bar{\textbf{x}}_{1} - \bar{\textbf{x}}_{2}) = (10^{-4})'
             fr'\begin{{bmatrix}}{covx1mx2inv[0,0]} & {covx1mx2inv[0,1]} \\ {covx1mx2inv[1,0]} & {covx1mx2inv[1,1]} \end{{bmatrix}}'
             fr'\begin{{bmatrix}}{xbard[0,0]:.1f} \\ {xbard[1,0]:.1f} \end{{bmatrix}} = '
             fr'\begin{{bmatrix}}{crit_lc[0,0]:.3f} \\ {crit_lc[1,0]:.3f} \end{{bmatrix}}'
             ))

'The most critical linear combination leading to the rejection of H0 has coefficient vector'

<IPython.core.display.Math object>